### ISSUE TITLE
How do I register this to work with elixir and browserify?

### ISSUE THREAD

**Issue by matfish2** [vuejs/babel-plugin-transform-vue-jsx#21]
Tried:

```
var elixir = require('laravel-elixir');

elixir.config.js.browserify.transformers.push({
    name: 'babel-plugin-transform-vue-jsx'
});
```

Got:

```
 dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/matanya/Sites/vue-tables-2/node_modules/module-deps/node_modules/readable-stream/lib/_stream_readable.js:527:8)
    at wrapTransform (/Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:543:11)
    at makeTransform (/Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:253:32)
    at /Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:226:9
    at Deps.getTransforms (/Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:231:7)
    at /Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:366:24
    at onresolve (/Users/matanya/Sites/vue-tables-2/node_modules/module-deps/index.js:178:14)
    at /Users/matanya/Sites/vue-tables-2/node_modules/browserify/index.js:487:17
    at LOOP (fs.js:1739:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by ktsn** [comment]
I'm not sure about `laravel-elixir`, but I guess you should add configuration of babelify because this plugin is for babel.

**Comment by chay22** [comment]
According to https://github.com/laravel/elixir/issues/585, for laravel-elixir 6 (if that's what you're with) should place any babel configuration in `.babelrc` file. Anyways, by judging from [the source](https://github.com/JeffreyWay/laravel-elixir-browserify/blob/master/browserify.js#L148), https://github.com/laravel/elixir/issues/376 solution should work.

```javascript
var elixir = require('laravel-elixir');

elixir.config.js.browserify.transformers
    .find(transformer => transformer.name === 'babelify')
    .options.plugins = [
        'babel-plugin-transform-vue-jsx'
       //or maybe require('babel-plugin-transform-vue-jsx')
    ];
```
If up both solutions don't work, if you're on laravel-elixir 6, and still needed to make its browserify task done right. Just downgrade to laravel elixir 5, as it always easier there.
