### ISSUE TITLE
how to solve this,tks!

### ISSUE THREAD

**Issue by yanlee26** [vuejs/babel-plugin-transform-vue-jsx#40]
ERROR in ./example.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "D:\\me\\vue\\babel-plugin-transform-vue-jsx"
    at D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:20)
    at OptionManager.mergePresets (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:10)
    at OptionManager.mergeOptions (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:244:14)
    at OptionManager.init (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-loader\lib\index.js:41:20)
    at Object.module.exports (D:\me\vue\babel-plugin-transform-vue-jsx\example\node_modules\babel-loader\lib\index.js:138:12)

**Comment by DevanB** [comment]
Are you getting this when you startup a Vue application?

**Comment by yanlee26** [comment]
yeah,absolutely..

**Comment by nickmessing** [comment]
@yanlee26, you forgot to install `babel-preset-es2015`

**Comment by DevanB** [comment]
Funny, I just came back to this, because I had this same problem again.

That's when I realized that the README does not specifically say to install `babel-preset-2015` in it's setup instructions.
