### ISSUE TITLE
TypeError: Cannot read property '$createElement' of null

### ISSUE THREAD

**Issue by krasevych** [vuejs/babel-plugin-transform-vue-jsx#74]
I use Nuxt and I have a code:
```
@Component({
  functional: true
})
class KrTransition extends Vue {
  render() {
    return <h1>hello</h1>;
  }
}

export default KrTransition;
```
when I try use it, I get a error:
```
TypeError: Cannot read property '$createElement' of null
    at render (src/components/KrTransition/KrTransition.js:8:11)
    at createFunctionalComponent (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3073:35)
    at createComponent (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3027:12)
    at _createElement (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3327:15)
    at createElement (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3281:10)
    at vm._c (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3569:42)
    at Proxy.render (src/components/ImageSlider/ImageSlider.vue?92ca:2:0)
    at VueComponent.Vue._render (D:\Projects\Vue\smart-landing\node_modules\vue\dist\vue.runtime.common.js:3605:22)
    at renderComponent (D:\Projects\Vue\smart-landing\node_modules\vue-server-renderer\build.js:6698:25)
    at RenderContext.renderNode (D:\Projects\Vue\smart-landing\node_modules\vue-server-renderer\build.js:6681:7)
```

**Comment by nickmessing** [comment]
@krasevych, for some reason `h` auto-injection doesn't work, you can try adding `h` as an argument for `render()` method. Can you please check what is `this` equal to in `render()`? is this really `null`?

**Comment by nickmessing** [comment]
Should be fixed if [vue#5534](https://github.com/vuejs/vue/pull/5534) gets merged.

**Comment by krasevych** [comment]
@nickmessing when I change to `render(createElement, context)` it works, thank you!
Yes, this equal to in render() is this really null.

**Comment by HerringtonDarkholme** [comment]
I would rather argue [auto injection](https://github.com/vuejs/babel-plugin-transform-vue-jsx#h-auto-injection) requires `this`. But functional component, by its definition, does not have `this` so you have to inject `createElement` yourself.

**Comment by nickmessing** [comment]
@HerringtonDarkholme, context is created anyway, it's just not passed as context into `render` method for some reason.

**Comment by nickmessing** [comment]
Weird thing tho, I always prefer vue's template compiler over JSX but still try to keep an eye on babel-plugin-transform-vue-jsx

**Comment by krasevych** [comment]
I use vue template compiler over JSX, but sometimes I need to use jsx for some difficult component manipulation

**Comment by nickmessing** [comment]
#76 solves this
