### ISSUE TITLE
Works with .babelrc but not with Browserify API

### ISSUE THREAD

**Issue by Harrisonbro** [vuejs/babel-plugin-transform-vue-jsx#79]
I'm using this plugin with Browserify and have found that it only works if I include it in a `.babelrc` file rather than via the Browserify API directly (without a `.babelrc` file).

#### Via `.babelrc` — works:
```JSON
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
```
*Example of this working configuration: [working.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019898/working.zip)*

#### Via Browserify API directly — doesn't work:
```Javascript
var bundler = browserify({ ... });

bundler.transform('babelify', {
    presets: ['es2015'],
    plugins: ['transform-vue-jsx'],
});

bundler.bundle().pipe( ... );
```
*Example of this broken configuration: [broken.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019897/broken.zip)*

- - -

Is there any reason it should only work when using `.babelrc` that I'm not aware of, or is this a bug?

For reference, I've attached a test project which includes some JSX code and a working configuration with Browserify (using a `.babelrc` file) and then a non-working version (using the Browserify API). 

To test either of the examples, unzip and `cd` into the directory, then run `npm install; npm run js;` (tested with Node v6.10.3). 

The working example (see [working.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019898/working.zip)) should output something like this when running `npm run js`: 

```
> vue-browserify-demo@1.0.0 js /path/to/vue-browserify-demo
> gulp js
[19:39:21] Using gulpfile /path/to/vue-browserify-demo/gulpfile.js
[19:39:21] Starting 'js'...
[19:39:23] Finished 'js' after 1.58 s
```

When running `npm run js` with the broken version (see [broken.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019897/broken.zip)) I get this error:

```
[19:34:26] Browserify error: SyntaxError: /path/to/vue-browserify-demo/src/js/components/home.vue: Unexpected token (7:19) while parsing file: /path/to/vue-browserify-demo/src/js/components/home.vue
   5 |     render(h) {
   6 |         if (Math.random() > 0.5) {
>  7 |             return <h1 class='foo' id='bar'>~~~~~~ home.vue jsx!</h1>;
     |                    ^
   8 |         }
   9 | 
  10 |         return <Dashboard
    at Parser.pp$5.raise (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:4452:13)
    at Parser.pp.unexpected (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3748:12)
    at Parser.pp$3.parseExprSubscripts (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3492:19)
    at Parser.pp$3.parseMaybeUnary (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3472:19)
    at Parser.pp$3.parseExprOps (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3402:19)
    at Parser.pp$3.parseMaybeConditional (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3379:19)
    at Parser.pp$3.parseMaybeAssign (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3342:19)
    at Parser.pp$3.parseExpression (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:3304:19)
    at Parser.pp$1.parseReturnStatement (/path/to/vue-browserify-demo/node_modules/babylon/lib/index.js:2078:26)
```

My I'm running Node v6.10.3 and NPM v3.10.10.

**Test configurations:**
To run, unzip the file and `cd` into the directory, then run `npm install; npm run js`.

- [working.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019898/working.zip) (via `.babelrc`)
- [broken.zip](https://github.com/vuejs/babel-plugin-transform-vue-jsx/files/1019897/broken.zip) (via Browserify API)

**Comment by nickmessing** [comment]
That's likely some problems with passing config from browserify to babel.

**Comment by Harrisonbro** [comment]
OK. Does that imply it's not this plugin specifically that's at fault?

**Comment by nickmessing** [comment]
@Harrisonbro, yes, we are testing on webpack by passing config to babel and babel-cli with `.babelrc`, both work fine.

**Comment by Harrisonbro** [comment]
OK, I'll take a look myself and raise an issue with the appropriate repo.

Can you give any suggestion of where I might start looking, or is Browserify entirely foreign to you?

**Comment by nickmessing** [comment]
@Harrisonbro, sorry, never used it.
